DELIMITER $$
CREATE TABLE akun (
  id_akun INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  role ENUM('ADMIN', 'PEGAWAI') NOT NULL,
  nama_lengkap VARCHAR(100),
  email VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE login (
  id_login INT AUTO_INCREMENT PRIMARY KEY,
    id_akun INT NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  waktu_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  role ENUM('ADMIN', 'PEGAWAI') NOT NULL,
  CONSTRAINT fk_login_akun FOREIGN KEY (id_akun)
    REFERENCES akun(id_akun) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE lokasi (
  id_lokasi INT AUTO_INCREMENT PRIMARY KEY,
  nama_lokasi VARCHAR(100) NOT NULL,
  deskripsi TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_nama_lokasi (nama_lokasi)
);

CREATE TABLE dispenser (
  id_dispenser INT AUTO_INCREMENT PRIMARY KEY,
  id_lokasi INT NOT NULL,
  kode_dispenser VARCHAR(50) NOT NULL UNIQUE,
  kondisi ENUM('AKTIF', 'RUSAK', 'PERBAIKAN') DEFAULT 'AKTIF',
  tanggal_pasang DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dispenser_lokasi FOREIGN KEY (id_lokasi)
    REFERENCES lokasi(id_lokasi) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE laporan_penggantian (
  id_laporan INT AUTO_INCREMENT PRIMARY KEY,
  id_dispenser INT NOT NULL,
  id_akun INT NOT NULL,
  jumlah_tisu INT NOT NULL,
  keterangan TEXT,
  waktu_penggantian TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lp_dispenser FOREIGN KEY (id_dispenser)
    REFERENCES dispenser(id_dispenser) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_lp_akun FOREIGN KEY (id_akun)
    REFERENCES akun(id_akun) ON DELETE CASCADE ON UPDATE CASCADE
);

DELIMITER ;